name: Build
on:
  - pull_request
  - push

jobs:
  Test:
    name: ${{ matrix.os }} ${{ matrix.nodeVersion }} Tests
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        nodeVersion: ["22.x"]
        os: [windows-latest]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.nodeVersion }}
      - name: Install dependencies
        run: yarn
      - name: Run tests
        run: yarn run test
        env:
          SNOOPLOGG: "*"