name: Build
on:
  - pull_request
  - push

jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      - name: Install dependencies
        run: yarn
      - name: Lint
        run: yarn run lint

  Test:
    needs: Lint
    name: ${{ matrix.os }} ${{ matrix.nodeVersion }} Tests
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        nodeVersion: ["14.x", "16.x", "18.x", "20.x", "22.x"]
        os: [ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.nodeVersion }}
      - name: Install dependencies
        run: yarn
      - name: Run tests
        run: yarn run test
        env:
          SNOOPLOGG: "*"

  MacOSTest:
    needs: Lint
    name: ${{ matrix.os }} ${{ matrix.nodeVersion }} Tests
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        nodeVersion: ["16.x", "18.x", "20.x", "22.x"]
        os: [macos-latest]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.nodeVersion }}
      - name: Install dependencies
        run: yarn
      - name: Run tests
        run: yarn run test
        env:
          SNOOPLOGG: "*"

  MacOS14Test:
    needs: Lint
    name: ${{ matrix.os }} ${{ matrix.nodeVersion }} Tests
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        nodeVersion: ["14.x"]
        os: [macos-latest]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.nodeVersion }}
          architecture: "x64"
      - name: Install dependencies
        run: yarn
      - name: Run tests
        run: yarn run test
        env:
          SNOOPLOGG: "*"