name: Build
on:
  - pull_request
  - push

jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install dependencies
        run: yarn
      - name: Lint
        run: yarn run gulp lint

  Test:
    needs: Lint
    name: ${{ matrix.os }} ${{ matrix.nodeVersion }} Tests
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # nodeVersion: [ '10.24.1', '12.22.1', '14.16.1', '16.0.0' ]
        # os: [ macos-latest, ubuntu-latest, windows-latest ]
        nodeVersion: [ '14.16.1' ]
        os: [ macos-latest, ubuntu-latest, windows-latest ]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.nodeVersion }}
      - name: Install dependencies
        run: yarn
      - name: Run tests
        run: yarn run test
        env:
          SNOOPLOGG: '*'
